import {
  homeOutline,
  menuOutline,
  closeOutline,
  arrowBackOutline,
  arrowForwardOutline,
  heartOutline,
  heart,
  pulseOutline,
  fitnessOutline,
  medkitOutline,
  bodyOutline,
  personOutline,
  person,
  peopleOutline,
  calendarOutline,
  timeOutline,
  todayOutline,
  checkmarkCircleOutline,
  warningOutline,
  informationCircleOutline,
  settingsOutline,
  logOutOutline,
  searchOutline,
  eyeOutline,
  eyeOffOutline,
  addOutline,
  chevronDownOutline,
  chevronForwardOutline,
  starOutline,
  star,
  callOutline,
  mailOutline,
  locationOutline,
  barChartOutline,
  trendingUpOutline,
  logoLinkedin,
  openOutline,
  shieldCheckmarkOutline,
  analyticsOutline,
  ribbonOutline,
  watchOutline,
  bluetoothOutline,
  flameOutline,
  walkOutline,
  moonOutline,
  barbellOutline,
  batteryFullOutline,
  batteryHalfOutline,
  batteryDeadOutline,
  unlinkOutline,
  refreshOutline,
} from 'ionicons/icons';

export const Icons = {
  // nav
  home: homeOutline,
  menu: menuOutline,
  close: closeOutline,
  arrowBack: arrowBackOutline,
  arrowForward: arrowForwardOutline,

  // health
  heart: heartOutline,
  heartFilled: heart,
  pulse: pulseOutline,
  fitness: fitnessOutline,
  medical: medkitOutline,
  body: bodyOutline,

  // people
  person: personOutline,
  personFilled: person,
  people: peopleOutline,
  doctor: medkitOutline,

  // calendar / time
  calendar: calendarOutline,
  time: timeOutline,
  today: todayOutline,

  // misc
  checkmark: checkmarkCircleOutline,
  warning: warningOutline,
  info: informationCircleOutline,
  settings: settingsOutline,
  logout: logOutOutline,
  search: searchOutline,
  eye: eyeOutline,
  eyeOff: eyeOffOutline,
  add: addOutline,
  chevronDown: chevronDownOutline,
  chevronRight: chevronForwardOutline,
  star: starOutline,
  starFilled: star,
  phone: callOutline,
  mail: mailOutline,
  location: locationOutline,
  chart: barChartOutline,
  barChart: barChartOutline,
  heartOutline: heartOutline,
  trending: trendingUpOutline,
  linkedin: logoLinkedin,
  link: openOutline,
  shield: shieldCheckmarkOutline,
  analytics: analyticsOutline,
  ribbon: ribbonOutline,

  // wearables / devices
  watch: watchOutline,
  bluetooth: bluetoothOutline,
  flame: flameOutline,
  walk: walkOutline,
  moon: moonOutline,
  scale: bodyOutline,
  barbell: barbellOutline,
  batteryFull: batteryFullOutline,
  batteryHalf: batteryHalfOutline,
  batteryDead: batteryDeadOutline,
  linkOff: unlinkOutline,
  refresh: refreshOutline,
};
